CREATE TABLE APPCONTENT (
	num NUMBER(*,0) CONSTRAINT pk_approval PRIMARY KEY,
	title VARCHAR2(2000),
	content NCLOB,
	line NUMBER(*,0),
	empno NUMBER(*,0),
	ollno NUMBER(*,0),
	CONSTRAINT fk_line_num FOREIGN KEY(line) REFERENCES APPROVALLINE(num),
	CONSTRAINT fk_aemp_num FOREIGN KEY(empno) REFERENCES EMPLOYEE(num),
	CONSTRAINT fk_oll_num FOREIGN KEY(ollno) REFERENCES ORDERLISTLIST(num)
);

CREATE SEQUENCE SEQ_APPCONTENT_no;