CREATE TABLE APPCLIENT (
	empno NUMBER(*,0),
	id VARCHAR2(50),
	CONSTRAINT fk_appclient_num FOREIGN KEY(empno) REFERENCES EMPLOYEE(num),
	CONSTRAINT fk_appclient_id FOREIGN KEY(id) REFERENCES CLIENT(id)
);