CREATE TABLE EMPLOYEE (
	num NUMBER(*,0),
	name VARCHAR2(40),
	dept VARCHAR2(40),
	spot VARCHAR2(40),
	PRIMARY KEY(num),
	CONSTRAINT FK_EMP_dept FOREIGN KEY(dept)
	REFERENCES DEPARTMENT(name),
	CONSTRAINT FK_EMP_spot FOREIGN KEY(spot)
	REFERENCES DEPARTMENT(name)
);

CREATE SEQUENCE SEQ_EMPLOYEE_no;