INSERT INTO PART (PART,
                  BRAND,
                  PRICE,
                  ETA,
                  MODEL,
                  VIN,
                  QTY,
                  POCODE,
                  ORDER_QTY)
     VALUES ('AK47',
             'AUDI',
             2000,
             NULL,
             'RIPLE',
             NULL,
             4,
             '1',
             2);

INSERT INTO PART (PART,
                  BRAND,
                  PRICE,
                  ETA,
                  MODEL,
                  VIN,
                  QTY,
                  POCODE,
                  ORDER_QTY)
     VALUES ('M4',
             'BMW',
             1100,
             NULL,
             'M16',
             NULL,
             2,
             '2',
             1);

INSERT INTO PART (PART,
                  BRAND,
                  PRICE,
                  ETA,
                  MODEL,
                  VIN,
                  QTY,
                  POCODE,
                  ORDER_QTY)
     VALUES ('K2',
             'KIA',
             5000,
             NULL,
             'GUN',
             NULL,
             8,
             '3',
             4);

INSERT INTO PART (PART,
                  BRAND,
                  PRICE,
                  ETA,
                  MODEL,
                  VIN,
                  QTY,
                  POCODE,
                  ORDER_QTY)
     VALUES ('EDD202',
             'JAPAN',
             70000,
             NULL,
             'SAKUYA',
             NULL,
             1,
             '2',
             56);

INSERT INTO PART (PART,
                  BRAND,
                  PRICE,
                  ETA,
                  MODEL,
                  VIN,
                  QTY,
                  POCODE,
                  ORDER_QTY)
     VALUES ('KITRI',
             'MSKIM',
             20,
             NULL,
             'MSKIM',
             NULL,
             2,
             '3',
             2);

INSERT INTO PART (PART,
                  BRAND,
                  PRICE,
                  ETA,
                  MODEL,
                  VIN,
                  QTY,
                  POCODE,
                  ORDER_QTY)
     VALUES ('A478',
             'BENZ',
             6800,
             NULL,
             's-class',
             NULL,
             4,
             '1',
             9);

COMMIT;