CREATE TABLE DEPARTMENT (
	num NUMBER(*,0) CONSTRAINT pk_department PRIMARY KEY,
	name VARCHAR2(40)
);

CREATE SEQUENCE SEQ_DEPARTMENT_no;

CREATE TABLE SPOT (
	num NUMBER(*,0) CONSTRAINT pk_spot PRIMARY KEY,
	name VARCHAR2(40)
);

CREATE SEQUENCE SEQ_SPOT_no;

CREATE TABLE EMPLOYEE (
	num NUMBER(*,0) CONSTRAINT pk_employee PRIMARY KEY,
	name VARCHAR2(40),
	dept VARCHAR2(40),
	spot VARCHAR2(40),
	CONSTRAINT fk_emp_dept_num FOREIGN KEY(dept) REFERENCES DEPARTMENT(name),
	CONSTRAINT fk_emp_spot_num FOREIGN KEY(spot) REFERENCES DEPARTMENT(name)
);

CREATE SEQUENCE SEQ_EMPLOYEE_no;

CREATE TABLE APPROVALLINE (
	num NUMBER(*,0) CONSTRAINT pk_approvalline PRIMARY KEY,
	seq NUMBER(*,0),
	empno NUMBER(*,0),
	CONSTRAINT fk_emp_num FOREIGN KEY(empno) REFERENCES EMPLOYEE(num),
	CONSTRAINT fk_emp_spot_num FOREIGN KEY(spot) REFERENCES SPOT(num)
);

CREATE SEQUENCE SEQ_APPROVALLINE_no;

CREATE TABLE ORDERLISTLIST (
	num NUMBER(*,0) CONSTRAINT pk_orderlistlist PRIMARY KEY,
	title VARCHAR2(4000)
);

CREATE SEQUENCE SEQ_ORDERLISTLIST_no;

CREATE TABLE APPROVAL (
	num NUMBER(*,0) CONSTRAINT pk_approval PRIMARY KEY,
	title VARCHAR2(4000),
	content NCLOB(*,0),
	line NUMBER(*,0),
	empno NUMBER(*,0),
	ollno NUMBER(*,0),
	CONSTRAINT fk_line_num FOREIGN KEY(line) REFERENCES APPROVALLINE(num),
	CONSTRAINT fk_emp_num FOREIGN KEY(empno) REFERENCES EMPLOYEE(num),
	CONSTRAINT fk_oll_num FOREIGN KEY(ollno) REFERENCES ORDERLISTLIST(num)
);

CREATE SEQUENCE SEQ_APPROVAL_no;